import { Category, ModelProvider, PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

type SeedChange = { title: string; description: string; category: Category; tags: string[]; modelId: string; temperature: number; maxTokens: number; promptContent: string; inputExample: string; outputExample: string };

const changes: SeedChange[] = [
  { title: "一键生成会议纪要", description: "把杂乱会议记录变成结构清晰、可直接发送的纪要。", category: Category.WORKPLACE, tags: ["会议", "效率", "GPT-4o"], modelId: "gpt-4o", temperature: 0.3, maxTokens: 800, promptContent: "你是一位资深行政助理，擅长整理会议记录。请将以下原始会议内容整理成一份结构清晰的会议纪要，包含：会议主题、参与人员（如果未提及则写“待补充”）、关键讨论点、决议事项、待办任务（含负责人和截止时间，如果未提及则留空）。使用 Markdown 格式。\n\n原始内容：\n{{input}}", inputExample: "今天开会讨论了新APP的发布计划，张三说下周三前完成UI设计，李四觉得需要再调研一下竞品，王五建议先做MVP。最后大家同意先做MVP，UI设计可以简化，李四负责竞品调研，周五给结果。", outputExample: "## 会议纪要\n**会议主题**：新APP发布计划讨论\n\n**参与人员**：张三、李四、王五（待补充）\n\n**关键讨论点**：\n- UI设计时间紧张，需在下周三前完成\n- 竞品调研不足，需要补充\n- 建议优先开发MVP\n\n**决议事项**：\n- 先做MVP，UI设计简化\n\n**待办任务**：\n- [ ] 完成UI设计（负责人：张三，截止：下周三）\n- [ ] 竞品调研并输出报告（负责人：李四，截止：本周五）" },
  { title: "周报快速撰写", description: "输入本周工作要点，自动生成条理清晰的周报。", category: Category.WORKPLACE, tags: ["周报", "汇报", "效率"], modelId: "gpt-4o", temperature: 0.4, maxTokens: 600, promptContent: "你是一位职场沟通专家，擅长撰写简洁专业的周报。请根据用户提供的工作内容，生成一份周报，包含：本周完成事项、下周计划、风险与求助。使用 Markdown 列表格式，语言简洁，每项不超过2行。\n\n工作内容：\n{{input}}", inputExample: "完成了首页改版的开发，修复了登录页的bug，参加了产品评审会，下周准备开始做用户中心模块，可能需要后端支持。", outputExample: "## 本周周报\n\n### 本周完成事项\n- 完成首页改版开发，已上线测试环境\n- 修复登录页在 Safari 下的兼容性 bug\n- 参与产品评审会，确认用户中心模块需求\n\n### 下周计划\n- 开始用户中心模块开发\n- 联调用户信息接口\n\n### 风险与求助\n- 用户中心模块需要后端提供数据接口，希望下周二前给出接口文档" },
  { title: "邮件润色", description: "把生硬的邮件改写成专业、得体、有礼貌的商务邮件。", category: Category.WORKPLACE, tags: ["邮件", "写作", "沟通"], modelId: "claude-3-5", temperature: 0.5, maxTokens: 500, promptContent: "你是一位商务沟通顾问，擅长将邮件改写得专业且礼貌。请润色以下邮件草稿，保留原意，但语气更加得体、结构清晰。如果有明显语法问题请修正。直接输出润色后的邮件，不要解释。\n\n草稿：\n{{input}}", inputExample: "王总，上次说的那个合同，你那边什么时候能签？我们这边等着开工。还有发票什么时候开？赶紧的。", outputExample: "王总，您好：\n\n关于上次沟通的合作合同，请问您这边预计什么时候可以完成签署？我们这边已经做好准备工作，希望能尽快推进项目启动。\n\n另外，发票开具的时间也请您方便时告知，以便我们安排后续财务流程。\n\n感谢您的支持，期待您的回复。\n\n祝好！\n[您的姓名]" },
  { title: "小红书爆款文案生成", description: "输入产品卖点，生成符合小红书风格的种草文案。", category: Category.CONTENT, tags: ["小红书", "种草", "文案"], modelId: "gpt-4o", temperature: 0.8, maxTokens: 700, promptContent: "你是一位小红书资深博主，擅长撰写高互动率的种草文案。请根据用户提供的产品信息，生成一篇小红书笔记文案，要求：标题吸引眼球（含emoji），正文使用口语化、活泼的语气，适当使用表情符号，结尾加上相关话题标签（3-5个）。\n\n产品信息：\n{{input}}", inputExample: "一款便携榨汁杯，无线充电，容量350ml，适合上班族，价格99元。", outputExample: "🌟 上班族福音！这个榨汁杯也太方便了吧！\n\n姐妹们！最近入手了一个宝藏榨汁杯，真的绝绝子！\n\n✨ 无线设计，充一次电能用一周，办公室、健身房都能用\n🍹 350ml容量，刚好一杯，不怕浪费\n💪 榨汁超细腻，打香蕉奶昔、草莓酸奶都超顺滑\n💰 才99块，性价比超高！\n\n#便携榨汁杯 #办公室好物 #健康生活 #上班族必备 #好物分享" },
  { title: "公众号文章大纲生成", description: "输入主题，生成逻辑清晰的文章大纲，含小标题和要点。", category: Category.CONTENT, tags: ["公众号", "大纲", "写作"], modelId: "claude-3-5", temperature: 0.5, maxTokens: 800, promptContent: "你是一位资深公众号主编，擅长策划文章结构。请根据用户提供的主题，生成一篇公众号文章的大纲，要求：包含吸引人的标题（可提供2-3个备选）、引言要点、正文分3-5个小节（每节有小标题和2-3个要点）、结尾总结或行动建议。使用 Markdown 格式。\n\n主题：\n{{input}}", inputExample: "如何利用AI提升工作效率", outputExample: "## 备选标题\n1. AI时代，这5个变化让你的工作效率翻倍\n2. 还在加班？用AI帮你每天省出2小时\n\n## 正文\n### 1. 会议纪要自动化\n- 使用AI整理会议记录\n- 5分钟生成结构化纪要\n### 2. 邮件智能润色\n- 不再纠结措辞\n- AI让邮件更专业得体\n\n## 结尾\n从一个变化开始，把时间留给更重要的事。" },
  { title: "短视频脚本生成", description: "输入主题和时长，生成带分镜的短视频脚本。", category: Category.CONTENT, tags: ["短视频", "脚本", "抖音"], modelId: "gpt-4o", temperature: 0.7, maxTokens: 700, promptContent: "你是一位短视频编导，擅长撰写有节奏、有吸引力的口播脚本。请根据用户提供的主题和时长要求，生成一个短视频脚本，包含：开场钩子、正文内容（分点）、结尾引导关注。请标注每部分的预估时间。\n\n主题和时长：\n{{input}}", inputExample: "主题：三个AI冷知识，时长60秒", outputExample: "【开场钩子】（0-5秒）\n这三个AI冷知识，知道一个算你厉害！\n\n【正文】（5-45秒）\n1. AI不仅能写文章，还能帮你处理图片。\n2. 输入法可能已经在用AI预测你要打什么字。\n3. AI可以模仿声音，听到名人说话别全信。\n\n【结尾引导】（45-60秒）\n你还知道哪些AI冷知识？留言告诉我。" },
  { title: "代码审查助手", description: "输入代码片段，获得代码质量、潜在bug和改进建议。", category: Category.DEVELOPMENT, tags: ["代码", "审查", "编程"], modelId: "claude-3-5", temperature: 0.2, maxTokens: 800, promptContent: "你是一位资深代码审查专家。请审查以下代码片段，指出：潜在bug、性能问题、可读性问题、安全隐患，并给出改进建议。如果代码没有明显问题，请说明理由。输出格式：分点列出，使用 Markdown。\n\n代码：\n{{input}}", inputExample: "def calculate_average(nums):\n    total = 0\n    for n in nums:\n        total += n\n    return total / len(nums)", outputExample: "- 潜在bug：如果 nums 为空列表，len(nums) 为 0，会抛出 ZeroDivisionError。\n- 改进建议：在函数开头增加 if not nums: return 0。\n- 可读性：变量 n 可以改为 num 更清晰。\n- 性能：可使用 sum(nums)。\n\n改进后代码：\ndef calculate_average(nums):\n    if not nums:\n        return 0\n    return sum(nums) / len(nums)" },
  { title: "SQL 查询优化", description: "输入SQL语句，分析性能瓶颈并给出优化版本。", category: Category.DEVELOPMENT, tags: ["SQL", "数据库", "优化"], modelId: "gpt-4o", temperature: 0.2, maxTokens: 600, promptContent: "你是一位数据库优化专家。请分析以下SQL查询，指出可能的性能问题（如全表扫描、未使用索引、子查询效率低等），并提供优化后的SQL语句。如果查询已经比较优化，请说明理由。\n\nSQL：\n{{input}}", inputExample: "SELECT * FROM orders WHERE customer_id IN (SELECT id FROM customers WHERE city = '上海') AND order_date > '2025-01-01';", outputExample: "问题：子查询可能导致多次执行，且 SELECT * 会检索所有列，增加 IO。\n\n优化建议：使用 JOIN 替代子查询，并只选择需要的列。\nSELECT o.order_id, o.order_date, o.amount\nFROM orders o\nJOIN customers c ON o.customer_id = c.id\nWHERE c.city = '上海' AND o.order_date > '2025-01-01';\n\n额外建议：确保 orders.customer_id 和 customers.city 上有索引。" },
  { title: "单元测试生成", description: "输入函数代码，自动生成覆盖主要分支的单元测试。", category: Category.DEVELOPMENT, tags: ["测试", "代码", "开发"], modelId: "claude-3-5", temperature: 0.2, maxTokens: 700, promptContent: "你是一位测试开发工程师。请为以下函数生成单元测试，使用 Python 的 pytest 框架。要求覆盖正常情况、边界条件、异常情况。每个测试用例前用注释说明测试目标。\n\n函数代码：\n{{input}}", inputExample: "def divide(a, b):\n    if b == 0:\n        raise ValueError('除数不能为0')\n    return a / b", outputExample: "import pytest\n\ndef test_divide_normal():\n    assert divide(10, 2) == 5.0\n\ndef test_divide_by_zero():\n    with pytest.raises(ValueError, match='除数不能为0'):\n        divide(10, 0)\n\ndef test_divide_float():\n    assert divide(1, 3) == pytest.approx(0.3333, rel=1e-3)" },
  { title: "复杂概念通俗化解释", description: "输入一个专业术语或概念，用小学生都能懂的语言解释。", category: Category.LEARNING, tags: ["学习", "概念", "通俗化"], modelId: "gpt-4o", temperature: 0.7, maxTokens: 500, promptContent: "你是一位擅长知识科普的老师。请用简单易懂的语言（可以打比方、举例子）解释以下概念，让完全没有背景的人也能听懂。解释控制在200字以内，最后可以加一个有趣的类比。\n\n概念：\n{{input}}", inputExample: "什么是区块链？", outputExample: "区块链就像一个所有人都能查看的公共账本，而且这个账本一旦记录就不能更改。想象一下，你和朋友们一起记账，每个人手里都有一个一模一样的本子。每次有人花钱，所有人都同时记下这笔账。如果有人想偷偷改自己的本子，别人一对比就会发现不对。\n\n有趣类比：区块链就像一群互相监督的证人，谁也别想撒谎。" },
  { title: "英语作文润色", description: "输入英文段落，纠正语法、提升表达地道性。", category: Category.LEARNING, tags: ["英语", "写作", "学习"], modelId: "claude-3-5", temperature: 0.4, maxTokens: 500, promptContent: "你是一位英语母语编辑。请润色以下英文段落，纠正语法错误、用词不当，使表达更加自然地道。如果原文没有错误，也请说明可以改进的地方。输出润色后的段落，并简要列出修改点（最多3条）。\n\n原文：\n{{input}}", inputExample: "I very like AI. It can help us do many things. But some people afraid AI will replace human. I think AI is a tool, we should use it wisely.", outputExample: "I really like AI. It can help us do many things. However, some people are afraid that AI will replace humans. I believe AI is a tool, and we should use it wisely.\n\n修改点：\n1. very like 改为 really like。\n2. some people afraid 补充 be 动词。\n3. replace human 改为 replace humans。" },
  { title: "商品标题优化", description: "输入商品基本信息，生成包含关键词、吸引点击的标题。", category: Category.ECOMMERCE, tags: ["电商", "标题", "运营"], modelId: "gpt-4o", temperature: 0.6, maxTokens: 300, promptContent: "你是一位电商运营专家，擅长撰写高点击率的商品标题。请根据以下商品信息，生成3个标题备选，要求包含核心关键词、卖点、规格等，总字数不超过30字。每个标题用一行输出。\n\n商品信息：\n{{input}}", inputExample: "无线蓝牙耳机，降噪，续航30小时，黑色，适合运动。", outputExample: "1. 真无线降噪耳机 运动跑步专用 30小时续航 黑色\n2. 蓝牙5.3降噪耳机 超长续航30h 防水防汗 黑色\n3. 运动蓝牙耳机 主动降噪 30小时续航 入耳式黑色" }
];

const extendedChanges: SeedChange[] = [
  { title: "面试回答打磨", description: "把零散经历整理成有重点、有证据的面试回答。", category: Category.WORKPLACE, tags: ["面试", "求职", "表达"], modelId: "claude-3-5", temperature: 0.4, maxTokens: 700, promptContent: "你是一位资深面试教练。根据候选人的经历和面试问题，使用 STAR 结构生成一段 90 秒内可说完的回答。必须保留真实信息；缺失的数据用【待补充】标注。最后列出 2 个可追问的问题。\n\n经历与问题：\n{{input}}", inputExample: "问题：你如何解决跨团队协作冲突？经历：我负责支付改版，设计认为流程太长，研发担心改动风险。我组织了两次评审，拿出埋点数据，最后先灰度简化流程。", outputExample: "我曾在支付改版中处理过一次跨团队分歧。设计希望简化流程，研发担心改动风险。我先组织评审并补充了旧流程埋点数据，确认主要流失发生在【待补充环节】。最终团队决定先灰度上线简化方案，并设置回滚阈值。结果是【待补充：转化或投诉数据】。\n\n可追问：1. 你如何推动没有直接汇报关系的团队？2. 灰度指标如何设计？" },
  { title: "需求评审风险清单", description: "输入需求描述，提前找出范围、依赖和验收风险。", category: Category.WORKPLACE, tags: ["需求", "评审", "项目管理"], modelId: "gpt-4o", temperature: 0.3, maxTokens: 700, promptContent: "你是一位产品交付负责人。审阅以下需求，输出：1. 不明确的范围；2. 外部依赖；3. 边界场景；4. 验收标准缺口；5. 评审会上应确认的问题。没有依据时不要臆测，用“待确认”标注。\n\n需求：\n{{input}}", inputExample: "用户可以在订单详情页申请退款，客服审核通过后原路退款，退款完成给用户发通知。", outputExample: "## 待确认范围\n- 是否支持部分退款、运费退款和多商品订单？\n- 哪些订单状态可以申请？\n\n## 依赖\n- 支付渠道原路退款接口\n- 客服审核权限与通知服务\n\n## 验收缺口\n- 未说明退款失败、重复提交和到账时效提示。" },
  { title: "视频口播开场钩子", description: "围绕一个主题生成不同风格的前三秒开场。", category: Category.CONTENT, tags: ["短视频", "口播", "选题"], modelId: "gpt-4o", temperature: 0.8, maxTokens: 500, promptContent: "你是短视频内容策划。根据主题、受众和平台，给出 6 个不夸张、不造假的口播开场钩子，覆盖提问、反差、清单、场景四种写法。每条不超过 28 字，并注明适合的画面或动作。\n\n主题信息：\n{{input}}", inputExample: "主题：上班族如何用 AI 整理会议纪要；受众：刚入职的产品经理；平台：视频号。", outputExample: "1. 会议一散就忘重点？试试这一个整理法。｜画面：凌乱笔记\n2. 别再熬夜补纪要了，五分钟先出骨架。｜画面：计时器\n3. 新人开会最怕漏什么？不是细节，是待办。｜画面：待办清单" },
  { title: "长文改短内容矩阵", description: "把一篇长文拆成多平台可发布的短内容。", category: Category.CONTENT, tags: ["改写", "矩阵", "分发"], modelId: "claude-3-5", temperature: 0.6, maxTokens: 900, promptContent: "你是一位内容编辑。将以下长文拆成：1 条公众号摘要、1 条小红书笔记提纲、1 条 60 秒口播提纲、3 条社媒短句。保留原文事实，不补充不存在的案例；说明各版本的目标受众。\n\n长文：\n{{input}}", inputExample: "我们团队把每周例会从90分钟缩短到35分钟，关键是会前收集议题、会上只决策、会后自动整理待办。", outputExample: "## 公众号摘要\n用会前议题、会中决策、会后待办三步，把例会从 90 分钟缩短到 35 分钟。\n\n## 60 秒口播\n开场：为什么会越开越长？\n核心：把信息同步移到会前，把决策留在会上。\n结尾：下次开会先试着只带三个待决问题。" },
  { title: "线上故障排查路径", description: "根据报错和现象生成分层排查顺序，减少盲查。", category: Category.DEVELOPMENT, tags: ["排障", "线上", "日志"], modelId: "claude-3-5", temperature: 0.2, maxTokens: 800, promptContent: "你是一位 SRE。根据故障现象，按“影响确认、快速止损、证据收集、假设验证、复盘记录”输出排查路径。每一步写明观察什么、可能结论和下一动作。不要建议危险操作；不确定处标注待确认。\n\n故障信息：\n{{input}}", inputExample: "接口 P95 从200ms升到4秒，错误率从0.1%升到3%，只发生在华东用户，最近刚上线推荐接口缓存改动。", outputExample: "1. 影响确认：按地域、接口和版本拆分 P95 与错误率，确认是否仅华东。\n2. 快速止损：评估回滚缓存改动或降级推荐接口，先保护主链路。\n3. 证据收集：查看缓存命中率、连接池、上游耗时与错误日志。\n4. 假设验证：若命中率下降且上游耗时升高，优先验证缓存 key 或地域路由。" },
  { title: "接口文档补全", description: "输入接口草稿，补齐调用方真正需要的说明。", category: Category.DEVELOPMENT, tags: ["API", "文档", "协作"], modelId: "gpt-4o", temperature: 0.3, maxTokens: 800, promptContent: "你是一位后端技术文档工程师。将接口草稿整理为 Markdown 文档，包含用途、鉴权、请求参数、响应示例、错误码、幂等性与调用注意事项。没有提供的信息标记为待确认，不要编造字段。\n\n接口草稿：\n{{input}}", inputExample: "POST /api/orders/:id/cancel，需要登录，传 reason，成功返回订单状态，已经发货不能取消。", outputExample: "## 取消订单\n`POST /api/orders/:id/cancel`\n\n### 鉴权\n需要登录，且订单归当前用户所有。\n\n### 请求参数\n- `reason`：取消原因，类型与是否必填待确认。\n\n### 错误码\n- `ORDER_SHIPPED`：订单已发货，不能取消。\n- 其他错误码待确认。" },
  { title: "知识点学习计划", description: "按照时间和基础，把学习目标拆成可执行的每日计划。", category: Category.LEARNING, tags: ["学习计划", "复习", "目标"], modelId: "gpt-4o", temperature: 0.5, maxTokens: 700, promptContent: "你是一位学习教练。根据学习目标、当前基础和可用时间，制定不超过 14 天的计划。每天包含：学习任务、主动回忆练习、预计时长和完成标志；保留 2 天复习或缓冲。任务必须具体，不要只写“学习相关内容”。\n\n学习信息：\n{{input}}", inputExample: "目标：两周内能看懂 Python 数据分析入门教程；基础：会一点 Excel，不会编程；每天40分钟。", outputExample: "第1天：安装环境并运行第一个 Notebook（40 分钟）；完成标志：能读入一张 CSV。\n第2天：认识表格列、筛选与缺失值（40 分钟）；主动回忆：不用看资料说出三种筛选条件。\n第6天：复习与补漏；完成标志：独立完成一次按条件筛选。" },
  { title: "论文阅读提问卡", description: "把一篇论文摘要转成带着问题读的阅读卡。", category: Category.LEARNING, tags: ["论文", "阅读", "研究"], modelId: "claude-3-5", temperature: 0.4, maxTokens: 700, promptContent: "你是一位研究助理。根据论文摘要生成阅读提问卡：研究问题、核心方法、数据或样本、主要结论、局限、与我研究的关联、阅读时要找证据的 3 个问题。只基于摘要，不能把推测写成事实。\n\n摘要：\n{{input}}", inputExample: "本文使用1200名在线学习者的行为数据，研究即时反馈频率与课程完成率的关系，发现每周一次的结构化反馈与更高完成率相关。", outputExample: "研究问题：反馈频率是否与课程完成率相关？\n方法：分析 1200 名在线学习者行为数据。\n局限：摘要未说明是否控制学习者基础差异。\n带着问题读：1. 完成率如何定义？2. 反馈内容是否一致？3. 是否存在自选择偏差？" },
  { title: "客服回复分级", description: "把用户问题改写成清晰、有边界的客服回复。", category: Category.ECOMMERCE, tags: ["客服", "售后", "沟通"], modelId: "gpt-4o", temperature: 0.4, maxTokens: 600, promptContent: "你是一位电商客服主管。根据用户问题和已知规则，输出：推荐回复、需要人工升级的条件、不能承诺的内容。语气礼貌、简洁，不虚构物流、库存或补偿信息。\n\n问题与规则：\n{{input}}", inputExample: "用户说耳机到货后左耳没声音，规则：签收7天内可换货，需提供订单号和故障视频。", outputExample: "推荐回复：很抱歉给您带来不便。请您提供订单号和左耳无声的简短视频，我们核实后会尽快为您安排后续处理。签收 7 天内符合条件可申请换货。\n\n人工升级：超过 7 天、订单异常或视频无法判断。\n\n不能承诺：未核实前不承诺具体补偿或发货时间。" },
  { title: "差评原因归纳", description: "输入评价文本，找出高频问题与可行动的改进项。", category: Category.ECOMMERCE, tags: ["评价", "洞察", "运营"], modelId: "claude-3-5", temperature: 0.3, maxTokens: 700, promptContent: "你是一位用户洞察分析师。归纳以下商品评价中的问题，按出现频率分组，区分事实反馈与情绪表达；每组给出一个可验证的改进动作。没有足够证据时说明样本不足。\n\n评价：\n{{input}}", inputExample: "续航没有宣传的久，用两天就没电。外观很好看。客服回复慢。包装有点破，不过东西没坏。", outputExample: "1. 续航预期不符（1条）：需核对宣传口径、测试条件与用户使用场景。\n2. 客服响应慢（1条）：检查首响时长并设置高峰期排班。\n3. 包装破损（1条）：抽检运输环节与外箱强度。\n正向反馈：外观好看（1条）。\n样本不足：当前仅 4 条反馈，不能判断高频程度。" },
  { title: "经营数据异常诊断", description: "根据指标变化提出优先排查方向，而不是直接下结论。", category: Category.DATA_ANALYSIS, tags: ["数据", "异常", "诊断"], modelId: "gpt-4o", temperature: 0.2, maxTokens: 800, promptContent: "你是一位业务数据分析师。根据指标波动，输出：异常描述、可能影响范围、优先验证的 3 个假设、需要补充的数据、建议的下一步动作。严格区分事实和假设，不要把相关性写成因果。\n\n指标信息：\n{{input}}", inputExample: "本周新用户注册环比下降18%，访问量只下降3%，安卓端下降25%，iOS基本持平；周二上线了安卓注册页改版。", outputExample: "事实：新用户注册环比下降 18%，主要集中在安卓端；访问量变化较小。\n优先假设：1. 注册页改版引入表单或兼容问题；2. 安卓渠道流量质量变化；3. 埋点口径变更。\n补充数据：安卓各版本转化漏斗、错误日志、渠道分布、埋点发布记录。\n下一步：先对比改版前后安卓注册页各步骤转化，并检查周二发布错误。" },
  { title: "周度数据复盘", description: "把一组业务数据整理成可供决策的周度复盘。", category: Category.DATA_ANALYSIS, tags: ["复盘", "报表", "指标"], modelId: "claude-3-5", temperature: 0.3, maxTokens: 800, promptContent: "你是一位经营分析师。将以下周度数据整理为复盘，依次写：关键变化、可能原因、需要验证的假设、下周动作和风险。数字必须准确引用原始数据，无法判断原因时明确写“待验证”。\n\n数据：\n{{input}}", inputExample: "GMV 120万，环比+8%；订单数+3%；客单价+5%；退款率从2.1%升到3.4%；活动期间新品销量占GMV的22%。", outputExample: "## 关键变化\n- GMV 环比增长 8%，订单数增长 3%，客单价增长 5%。\n- 退款率由 2.1% 升至 3.4%。\n\n## 待验证\n新品销量占 GMV 22%，需核对退款上升是否集中在新品或活动渠道。\n\n## 下周动作\n按商品和渠道拆解退款原因，优先处理退款率异常的组合。" },
  { title: "旅行行程排布", description: "按时间、预算和偏好生成留有余量的旅行计划。", category: Category.LIFE, tags: ["旅行", "行程", "计划"], modelId: "gpt-4o", temperature: 0.6, maxTokens: 800, promptContent: "你是一位旅行规划助手。根据目的地、天数、偏好、预算和交通限制，生成按早中晚安排的行程。每天只安排 2 至 3 个重点，并预留通勤和休息时间；不确定的营业信息标注需自行确认。\n\n旅行信息：\n{{input}}", inputExample: "上海3天，喜欢美术馆和街区散步，预算每天800元，住在静安寺附近，不想赶行程。", outputExample: "第1天：上午在静安寺附近慢逛；下午选择一间美术馆（营业时间需确认）；晚上在武定路附近用餐。\n第2天：上午前往西岸，下午沿江散步并预留咖啡休息；晚上自由安排。\n第3天：只保留一个想二刷的地点，下午回酒店取行李。" },
  { title: "一周饮食备餐", description: "根据人数、预算和忌口安排可执行的备餐清单。", category: Category.LIFE, tags: ["饮食", "备餐", "健康"], modelId: "claude-3-5", temperature: 0.5, maxTokens: 700, promptContent: "你是一位家庭备餐规划师。根据人数、预算、忌口、可用厨具和工作日时间，给出 5 天晚餐计划、一次采购清单和周末预处理步骤。优先复用食材，避免给出医疗或营养治疗建议。\n\n条件：\n{{input}}", inputExample: "两个人，工作日每晚30分钟，不吃香菜，只有炒锅和电饭煲，预算300元。", outputExample: "周一：番茄鸡蛋盖饭；周二：青椒牛肉炒饭；周三：菌菇鸡腿电饭煲饭；周四：蒜蓉西兰花配煎豆腐；周五：剩余食材杂蔬面。\n\n周末预处理：鸡腿分装腌制、蔬菜洗净分盒、米饭食材按两餐份量准备。\n\n采购清单：鸡蛋、鸡腿、牛肉、番茄、西兰花、菌菇、青椒、豆腐、面条、米。" }
];

async function main() {
  await prisma.model.createMany({ data: [{ id: "gpt-4o", name: "GPT-4o", provider: ModelProvider.OPENAI }, { id: "claude-3-5", name: "Claude 3.5 Sonnet", provider: ModelProvider.ANTHROPIC }, { id: "gemini-1-5", name: "Gemini 1.5 Pro", provider: ModelProvider.GOOGLE }], skipDuplicates: true });
  const author = await prisma.user.upsert({ where: { email: "system@di73bian.com" }, update: { name: "第73变官方" }, create: { email: "system@di73bian.com", name: "第73变官方" } });
  for (const change of [...changes, ...extendedChanges]) {
    const existing = await prisma.technique.findFirst({ where: { authorId: author.id, title: change.title }, select: { id: true } });
    if (existing) continue;
    await prisma.$transaction(async (tx) => {
      const technique = await tx.technique.create({ data: { title: change.title, description: change.description, category: change.category, authorId: author.id, published: true, tags: { connectOrCreate: change.tags.map((name) => ({ where: { name }, create: { name } })) } } });
      const version = await tx.techniqueVersion.create({ data: { techniqueId: technique.id, versionNumber: 1, promptContent: change.promptContent, modelId: change.modelId, temperature: change.temperature, maxTokens: change.maxTokens, inputExample: change.inputExample, outputExample: change.outputExample, changelog: "初始变化" } });
      await tx.technique.update({ where: { id: technique.id }, data: { currentVersionId: version.id } });
    });
  }
  console.log(`已导入 ${changes.length + extendedChanges.length} 条精选变化。`);
}

main().catch((error) => { console.error(error); process.exitCode = 1; }).finally(() => prisma.$disconnect());
