"use client";

import { useEffect, useState } from "react";
import ReactMarkdown from "react-markdown";
import { CornerDownRight, Send, Trash2 } from "lucide-react";
import { useSession } from "next-auth/react";
import { useRouter } from "next/navigation";
import { formatDate } from "@/lib/utils";
import { EmptyState } from "@/components/empty-state";

type Comment = { id: string; content: string; createdAt: string; user: { id: string; name: string | null; image: string | null }; replies: Comment[] };

function Avatar({ user }: { user: Comment["user"] }) { return <div className="grid h-9 w-9 shrink-0 place-items-center overflow-hidden rounded-full border border-gold bg-mist text-xs font-semibold text-teal">{user.image ? <img src={user.image} alt="" className="h-full w-full object-cover" /> : (user.name || "变友").slice(0, 1)}</div>; }
function Markdown({ content }: { content: string }) { return <div className="prose prose-sm max-w-none break-words text-ink prose-p:my-1 prose-pre:overflow-x-auto"><ReactMarkdown>{content}</ReactMarkdown></div>; }

export function CommentSection({ changeId, currentUserId }: { changeId: string; currentUserId?: string }) {
  const { data: session } = useSession(); const router = useRouter(); const [comments, setComments] = useState<Comment[]>([]); const [content, setContent] = useState(""); const [reply, setReply] = useState<{ id: string; name: string } | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  useEffect(() => { fetch(`/api/changes/${changeId}/comments`).then((response) => response.ok ? response.json() : []).then(setComments).catch(() => setComments([])); }, [changeId]);
  const submit = async () => { if (!session) return router.push("/login"); const trimmed = content.trim(); if (!trimmed) return; setBusy(true); setError(""); try { const response = await fetch(`/api/changes/${changeId}/comments`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ content: trimmed, parentId: reply?.id }) }); const created = await response.json(); if (!response.ok) throw new Error(created.error || "变化心得没有留下"); setComments((current) => reply ? current.map((item) => item.id === reply.id ? { ...item, replies: [...item.replies, { ...created, replies: [] }] } : item) : [...current, { ...created, replies: [] }]); setContent(""); setReply(null); } catch (cause) { setError(cause instanceof Error ? cause.message : "变化心得没有留下"); } finally { setBusy(false); } };
  const remove = async (id: string, parentId?: string) => { const response = await fetch(`/api/comments/${id}`, { method: "DELETE" }); if (!response.ok) return; setComments((current) => parentId ? current.map((item) => item.id === parentId ? { ...item, replies: item.replies.filter((replyItem) => replyItem.id !== id) } : item) : current.filter((item) => item.id !== id)); };
  const renderComment = (comment: Comment, parentId?: string) => <article key={comment.id} className={parentId ? "border-l-2 border-gold pl-4" : ""}><div className="flex gap-3"><Avatar user={comment.user}/><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-x-2 text-sm"><span className="font-medium">{comment.user.name || "匿名变友"}</span><span className="muted text-xs">{formatDate(comment.createdAt)}</span></div><div className="mt-1"><Markdown content={comment.content}/></div><div className="mt-2 flex items-center gap-3"><button onClick={() => { setReply({ id: parentId || comment.id, name: comment.user.name || "匿名变友" }); setContent(""); }} className="inline-flex h-9 items-center gap-1 text-xs font-medium text-teal hover:text-coral"><CornerDownRight size={14}/>回复</button>{currentUserId === comment.user.id && <button title="删去变化心得" onClick={() => remove(comment.id, parentId)} className="muted grid h-9 w-9 place-items-center hover:text-failure"><Trash2 size={14}/></button>}</div></div></div>{!parentId && comment.replies.length > 0 && <div className="mt-3 space-y-4 pl-12">{comment.replies.map((item) => renderComment(item, comment.id))}</div>}</article>;
  return <section className="mt-10 border-t pt-8"><h2 className="text-xl font-bold">变化心得</h2><div className="sticky bottom-16 z-10 mt-4 bg-[var(--paper)] py-2 md:static md:bg-transparent md:py-0"><div className="panel p-4"><div className="mb-2 flex items-center justify-between gap-3"><label htmlFor={`comment-${changeId}`} className="text-sm font-medium">{reply ? `回复 ${reply.name}` : "留下你的变化心得"}</label>{reply && <button onClick={() => setReply(null)} className="muted text-xs hover:text-coral">取消回复</button>}</div><textarea id={`comment-${changeId}`} value={content} onChange={(event) => setContent(event.target.value)} maxLength={2000} placeholder={session ? "支持 Markdown 格式" : "登录后留下变化心得"} disabled={!session} className="min-h-28 w-full border p-3 text-sm outline-none focus:border-coral disabled:bg-mist" style={{ borderRadius: 4, background: "var(--paper)" }} /><div className="mt-2 flex items-center justify-between"><span className="muted text-xs">{content.length}/2000</span><button disabled={busy || !content.trim()} onClick={submit} className="inline-flex h-11 items-center gap-2 bg-coral px-4 text-sm font-medium text-white hover:bg-[#A31D20] disabled:opacity-50" style={{ borderRadius: 4 }}><Send size={15}/>{busy ? <span className="ellipsis">留下中</span> : "留下心得"}</button></div>{error && <p className="mt-2 text-sm text-failure">{error}</p>}</div></div><div className="mt-6 space-y-6">{comments.length ? comments.map((comment) => renderComment(comment)) : <EmptyState title="还没有变化心得" description="先试一变，再留下第一句真实感受。" actionHref="#run-panel" actionLabel="马上试变" />}</div></section>;
}
