"use client";

import { useState } from "react";
import { ChevronDown, ChevronUp } from "lucide-react";
import { formatDate, voteLabels } from "@/lib/utils";
import { VoteValue } from "@prisma/client";
import { EmptyState } from "@/components/empty-state";

type HistoryRun = { id: string; input: string; output: string | null; createdAt: string; user: { name: string | null; image: string | null }; vote: VoteValue | null };

export function RunHistory({ changeId, initialRuns, initialCursor }: { changeId: string; initialRuns: HistoryRun[]; initialCursor: string | null }) {
  const [runs, setRuns] = useState(initialRuns); const [cursor, setCursor] = useState(initialCursor); const [expanded, setExpanded] = useState<string | null>(null); const [loading, setLoading] = useState(false);
  const loadMore = async () => { if (!cursor) return; setLoading(true); try { const response = await fetch(`/api/changes/${changeId}/runs?cursor=${encodeURIComponent(cursor)}`); const data = await response.json(); if (response.ok) { setRuns((current) => [...current, ...data.items]); setCursor(data.nextCursor); } } finally { setLoading(false); } };
  return <section className="mt-7"><h2 className="mb-3 font-serif text-xl font-bold">大家的试变</h2>{runs.length ? <div className="space-y-3">{runs.map((run) => { const open = expanded === run.id; const summary = run.output ? `${run.output.slice(0, 200)}${run.output.length > 200 ? "..." : ""}` : "这次试变没有输出"; return <article key={run.id} className="panel overflow-hidden"><button onClick={() => setExpanded(open ? null : run.id)} className="flex min-h-14 w-full items-center gap-3 p-4 text-left hover:bg-mist"><div className="grid h-9 w-9 shrink-0 place-items-center overflow-hidden rounded-full border border-gold bg-mist text-xs font-semibold text-teal">{run.user.image ? <img src={run.user.image} alt="" className="h-full w-full object-cover" /> : (run.user.name || "变友").slice(0, 1)}</div><div className="min-w-0 flex-1"><div className="muted flex flex-wrap items-center gap-x-2 text-xs"><span>{run.user.name || "匿名变友"}</span><span>{formatDate(run.createdAt)}</span>{run.vote && <span className="font-medium text-moss">{voteLabels[run.vote]}</span>}</div><p className="mt-1 line-clamp-2 whitespace-pre-wrap text-sm leading-6 text-ink">{summary}</p></div>{open ? <ChevronUp size={18} className="muted shrink-0" /> : <ChevronDown size={18} className="muted shrink-0" />}</button>{open && <div className="border-t bg-mist p-4 text-sm"><p className="font-medium">试变输入</p><pre className="mt-2 whitespace-pre-wrap font-sans leading-6 text-ink">{run.input}</pre><p className="mt-4 font-medium">试变结果</p><pre className="mt-2 whitespace-pre-wrap font-sans leading-6 text-ink">{run.output || "这次试变没有输出"}</pre></div>}</article>; })}</div> : <EmptyState title="还没有公开试变记录" description="先试一变，把你的结果留在这里。" actionHref="#run-panel" actionLabel="马上试变" />}{cursor && <button disabled={loading} onClick={loadMore} className="mt-4 inline-flex h-11 items-center gap-2 border px-4 text-sm font-medium hover:border-coral hover:text-coral disabled:opacity-50" style={{ borderRadius: 4 }}>{loading ? <span className="ellipsis">加载中</span> : "加载更多"}</button>}</section>;
}
