CREATE TYPE "Category" AS ENUM ('WORKPLACE', 'CONTENT', 'DEVELOPMENT', 'LEARNING', 'ECOMMERCE', 'DATA_ANALYSIS', 'LIFE');
CREATE TYPE "VoteValue" AS ENUM ('VALID', 'PARTIAL', 'INVALID');
CREATE TYPE "RunStatus" AS ENUM ('SUCCESS', 'ERROR', 'TIMEOUT');
CREATE TYPE "ModelProvider" AS ENUM ('OPENAI', 'ANTHROPIC', 'GOOGLE');

CREATE TABLE "User" ("id" TEXT NOT NULL, "name" TEXT, "email" TEXT, "image" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "User_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Technique" ("id" TEXT NOT NULL, "title" TEXT NOT NULL, "description" TEXT NOT NULL, "category" "Category" NOT NULL, "authorId" TEXT NOT NULL, "published" BOOLEAN NOT NULL DEFAULT false, "currentVersionId" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Technique_pkey" PRIMARY KEY ("id"));
CREATE TABLE "TechniqueVersion" ("id" TEXT NOT NULL, "techniqueId" TEXT NOT NULL, "versionNumber" INTEGER NOT NULL, "promptContent" TEXT NOT NULL, "modelId" TEXT NOT NULL, "temperature" DOUBLE PRECISION NOT NULL DEFAULT 0.7, "maxTokens" INTEGER NOT NULL DEFAULT 1024, "inputExample" TEXT, "outputExample" TEXT, "changelog" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "TechniqueVersion_pkey" PRIMARY KEY ("id"));
CREATE TABLE "TechniqueRun" ("id" TEXT NOT NULL, "techniqueId" TEXT NOT NULL, "versionId" TEXT NOT NULL, "userId" TEXT NOT NULL, "input" TEXT NOT NULL, "output" TEXT, "model" TEXT NOT NULL, "status" "RunStatus" NOT NULL, "durationMs" INTEGER, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "TechniqueRun_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Vote" ("id" TEXT NOT NULL, "runId" TEXT NOT NULL, "userId" TEXT NOT NULL, "value" "VoteValue" NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "Vote_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Collection" ("id" TEXT NOT NULL, "userId" TEXT NOT NULL, "techniqueId" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "Collection_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Tag" ("id" TEXT NOT NULL, "name" TEXT NOT NULL, CONSTRAINT "Tag_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Model" ("id" TEXT NOT NULL, "name" TEXT NOT NULL, "provider" "ModelProvider" NOT NULL, "isActive" BOOLEAN NOT NULL DEFAULT true, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Model_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Account" ("id" TEXT NOT NULL, "userId" TEXT NOT NULL, "type" TEXT NOT NULL, "provider" TEXT NOT NULL, "providerAccountId" TEXT NOT NULL, "refresh_token" TEXT, "access_token" TEXT, "expires_at" INTEGER, "token_type" TEXT, "scope" TEXT, "id_token" TEXT, "session_state" TEXT, CONSTRAINT "Account_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Session" ("id" TEXT NOT NULL, "sessionToken" TEXT NOT NULL, "userId" TEXT NOT NULL, "expires" TIMESTAMP(3) NOT NULL, CONSTRAINT "Session_pkey" PRIMARY KEY ("id"));
CREATE TABLE "VerificationToken" ("identifier" TEXT NOT NULL, "token" TEXT NOT NULL, "expires" TIMESTAMP(3) NOT NULL);
CREATE TABLE "_TagToTechnique" ("A" TEXT NOT NULL, "B" TEXT NOT NULL);

CREATE UNIQUE INDEX "User_email_key" ON "User"("email");
CREATE INDEX "User_createdAt_idx" ON "User"("createdAt");
CREATE UNIQUE INDEX "Technique_currentVersionId_key" ON "Technique"("currentVersionId");
CREATE INDEX "Technique_category_published_createdAt_idx" ON "Technique"("category", "published", "createdAt");
CREATE INDEX "Technique_authorId_createdAt_idx" ON "Technique"("authorId", "createdAt");
CREATE INDEX "Technique_published_updatedAt_idx" ON "Technique"("published", "updatedAt");
CREATE UNIQUE INDEX "TechniqueVersion_techniqueId_versionNumber_key" ON "TechniqueVersion"("techniqueId", "versionNumber");
CREATE INDEX "TechniqueVersion_techniqueId_createdAt_idx" ON "TechniqueVersion"("techniqueId", "createdAt");
CREATE INDEX "TechniqueVersion_modelId_idx" ON "TechniqueVersion"("modelId");
CREATE INDEX "TechniqueRun_techniqueId_createdAt_idx" ON "TechniqueRun"("techniqueId", "createdAt");
CREATE INDEX "TechniqueRun_userId_createdAt_idx" ON "TechniqueRun"("userId", "createdAt");
CREATE INDEX "TechniqueRun_versionId_idx" ON "TechniqueRun"("versionId");
CREATE UNIQUE INDEX "Vote_runId_key" ON "Vote"("runId");
CREATE INDEX "Vote_userId_createdAt_idx" ON "Vote"("userId", "createdAt");
CREATE UNIQUE INDEX "Collection_userId_techniqueId_key" ON "Collection"("userId", "techniqueId");
CREATE INDEX "Collection_userId_createdAt_idx" ON "Collection"("userId", "createdAt");
CREATE INDEX "Collection_techniqueId_idx" ON "Collection"("techniqueId");
CREATE UNIQUE INDEX "Tag_name_key" ON "Tag"("name");
CREATE INDEX "Tag_name_idx" ON "Tag"("name");
CREATE UNIQUE INDEX "Model_name_key" ON "Model"("name");
CREATE INDEX "Model_provider_isActive_idx" ON "Model"("provider", "isActive");
CREATE UNIQUE INDEX "Account_provider_providerAccountId_key" ON "Account"("provider", "providerAccountId");
CREATE INDEX "Account_userId_idx" ON "Account"("userId");
CREATE UNIQUE INDEX "Session_sessionToken_key" ON "Session"("sessionToken");
CREATE INDEX "Session_userId_idx" ON "Session"("userId");
CREATE UNIQUE INDEX "VerificationToken_token_key" ON "VerificationToken"("token");
CREATE UNIQUE INDEX "VerificationToken_identifier_token_key" ON "VerificationToken"("identifier", "token");
CREATE UNIQUE INDEX "_TagToTechnique_AB_unique" ON "_TagToTechnique"("A", "B");
CREATE INDEX "_TagToTechnique_B_index" ON "_TagToTechnique"("B");

ALTER TABLE "Technique" ADD CONSTRAINT "Technique_authorId_fkey" FOREIGN KEY ("authorId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Technique" ADD CONSTRAINT "Technique_currentVersionId_fkey" FOREIGN KEY ("currentVersionId") REFERENCES "TechniqueVersion"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "TechniqueVersion" ADD CONSTRAINT "TechniqueVersion_techniqueId_fkey" FOREIGN KEY ("techniqueId") REFERENCES "Technique"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "TechniqueVersion" ADD CONSTRAINT "TechniqueVersion_modelId_fkey" FOREIGN KEY ("modelId") REFERENCES "Model"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "TechniqueRun" ADD CONSTRAINT "TechniqueRun_techniqueId_fkey" FOREIGN KEY ("techniqueId") REFERENCES "Technique"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "TechniqueRun" ADD CONSTRAINT "TechniqueRun_versionId_fkey" FOREIGN KEY ("versionId") REFERENCES "TechniqueVersion"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "TechniqueRun" ADD CONSTRAINT "TechniqueRun_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Vote" ADD CONSTRAINT "Vote_runId_fkey" FOREIGN KEY ("runId") REFERENCES "TechniqueRun"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Vote" ADD CONSTRAINT "Vote_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Collection" ADD CONSTRAINT "Collection_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Collection" ADD CONSTRAINT "Collection_techniqueId_fkey" FOREIGN KEY ("techniqueId") REFERENCES "Technique"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Account" ADD CONSTRAINT "Account_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Session" ADD CONSTRAINT "Session_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "_TagToTechnique" ADD CONSTRAINT "_TagToTechnique_A_fkey" FOREIGN KEY ("A") REFERENCES "Tag"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "_TagToTechnique" ADD CONSTRAINT "_TagToTechnique_B_fkey" FOREIGN KEY ("B") REFERENCES "Technique"("id") ON DELETE CASCADE ON UPDATE CASCADE;
